#!/usr/bin/env php
<?php
namespace jp3cki\homado\bin;

use jp3cki\homado\Application;
use jp3cki\homado\Config;

require_once(__DIR__ . '/vendor/autoload.php');

$app = new Application(
    new Config(__DIR__ . '/config/config.yml')
);
$app->run();
